import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
} from 'typeorm'
import { ChatThread } from './chatThread.entity'
import { EReportType } from '../enums/report.enum'

/**
 * Report entity represents a report generated by the user.
 */
@Entity('reports')
export class Report {
  @PrimaryGeneratedColumn('uuid')
  id: string

  @Column({ type: 'uuid', name: 'thread_id' })
  threadId: string

  @ManyToOne(() => ChatThread, (thread) => thread.reports, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'thread_id' })
  thread?: ChatThread

  @Column({ type: 'text', name: 'file_name' })
  fileName: string

  @Column({ type: 'text', name: 'file_url' })
  fileUrl: string

  @Column({
    type: 'varchar',
    name: 'file_type',
    length: 255,
  })
  fileType: string

  @Column({
    type: 'varchar',
    name: 'report_type',
    length: 255,
  })
  reportType?: EReportType

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt?: Date // Auto-set when the message is created

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt?: Date //Auto-updated when the message is modified
}
